version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn core.wsgi
    env_file:
      - ./backend/.env
    expose:
        - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:80
  
  db:
    image: postgres:latest
    volumes:
      - "$PWD/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mentoringhubdb
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
