#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput
gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker
# python manage.py runserver 0.0.0.0:8000
