# Generated by Django 3.2 on 2022-07-29 10:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('participants', models.JSONField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CANCELED', 'CANCELED'), ('ENDED', 'ENDED')], max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
