# Generated by Django 3.2 on 2022-09-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='token',
        ),
    ]
