# Generated by Django 3.2 on 2022-09-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_meeting_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='country',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_date',
        ),
    ]
