# Generated by Django 3.2 on 2022-09-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20220923_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
