# Generated by Django 3.2 on 2022-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('qna', models.JSONField(null=True)),
                ('mentor_id', models.CharField(max_length=100)),
                ('mentee_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('available', models.DateTimeField(null=True)),
                ('available_hour', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
