# Generated by Django 3.2 on 2022-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='available',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='available_hour',
            field=models.IntegerField(null=True),
        ),
    ]
