# Generated by Django 3.2 on 2022-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0003_auto_20220921_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='available_hour',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
