# Generated by Django 3.2 on 2022-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], max_length=10, verbose_name='Role of user'),
        ),
    ]
