# Generated by Django 3.2 on 2022-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220922_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10, null=True, verbose_name='Enter your gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MENTOR', 'mentor'), ('MENTEE', 'mentee')], max_length=10, verbose_name='Role of user'),
        ),
    ]
